server:
  port: 9994
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:tcp://localhost/~/SpringBootWeb
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
